### ISSUE TITLE
Better sudo detection/integration

### ISSUE THREAD

**Issue by andremedeiros** [andremedeiros/loon#39]
I don't want sudo required commands to just hang when waiting for a password.

We need to find a way where we can detect if a user is `nopasswd` or not before even executing, or have the password prompt work as intended.

**Comment by andremedeiros** [comment]
`sudo -n true` (`-n` is non interactive mode) works on Linux. Need to check macOS.

**Comment by eljojo** [comment]
related to this, I had an issue when it would almost ask for the password in the background, it was very weird but I could only type password for a few characters and then it'd "lose stdin".
my fix was to run sudo for another command before loon so i'm "pre-authenticated" and then it just works fine.

**Comment by andremedeiros** [comment]
Yeah, it doesn't work great if you don't have `nopasswd` setup.

I think what I need to do is run a preflight, check what stuff needs to be done, and then pre-emptively ask for sudo unless nopasswd is set.
